# Destroy everything.
- name: Destroy everything related to the reproducer runner instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: destroy the instance
      os_server:
        state: absent
        cloud: openstack
        name: "{{ reproducer_instance_name|default('chem-reproducer') }}"
        image: "CentOS-8-x86_64-GenericCloud-released-latest"
        availability_zone: nova
        flavor: "m1.medium"
        network: "reproducer-net"
        floating_ip_pools: provider_net_shared_3
        delete_fip: yes
        key_name: reproducer
        security_groups:
          - reproducer-security-group

    - name: destroy a router
      os_router:
        cloud: openstack
        state: absent
        name: reproducer-router
        network: provider_net_shared_3
        interfaces:
          - reproducer-subnet

    - name: destroy the reproducer subnet
      os_subnet:
        cloud: openstack
        state: absent
        name: reproducer-subnet
        network_name: reproducer-net
        enable_dhcp: yes
        cidr: 192.168.0.0/24
        dns_nameservers:
           - 10.11.5.19
           - 10.10.160.2
           - 10.5.30.160
           - 8.8.8.7
           - 8.8.8.8
        wait: yes

    - name: destroy the reproducer network
      os_network:
        cloud: openstack
        state: absent
        name: reproducer-net
        external: false
        shared: no
        wait: yes

    - name: destroy security group rule for ping
      os_security_group_rule:
        cloud: openstack
        state: absent
        security_group: reproducer-security-group
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0

    - name: destroy security group rule for SSH
      os_security_group_rule:
        cloud: openstack
        state: absent
        security_group: reproducer-security-group
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

    - name: destroy security group rule for Gerrit
      os_security_group_rule:
        cloud: "{{ cloud|default('openstack') }}"
        state: absent
        security_group: reproducer-security-group
        protocol: tcp
        port_range_min: 8080
        port_range_max: 8080
        remote_ip_prefix: 0.0.0.0/0

    - name: create security group rule for Zuul
      os_security_group_rule:
        cloud: "{{ cloud|default('openstack') }}"
        state: absent
        security_group: reproducer-security-group
        protocol: tcp
        port_range_min: 9000
        port_range_max: 9000
        remote_ip_prefix: 0.0.0.0/0

    - name: destroy security group
      os_security_group:
        cloud: openstack
        state: absent
        name: reproducer-security-group
        description: Security group for reproducer instances

    - name: Destroy the key
      os_keypair:
        state: absent
        cloud: "{{ cloud|default('openstack') }}"
        name: reproducer
        public_key_file: ./reproducer.pub
